import { useState } from "react";
import type { SemanticDraft, SemanticTable } from "../types";
import { Icon } from "./Icon";

type Props = { table: SemanticTable; isBusy: boolean; error: string | null; onBack: () => void; onUpdate: (draft: SemanticDraft, patch: Partial<SemanticDraft>) => Promise<void> };

export function SemanticTableDetail({ table, isBusy, error, onBack, onUpdate }: Props) {
  const [editing, setEditing] = useState<number | null>(null);
  const [draftValues, setDraftValues] = useState<Record<number, Partial<SemanticDraft>>>({});
  const beginEdit = (draft: SemanticDraft) => { setEditing(draft.id); setDraftValues((current) => ({ ...current, [draft.id]: { display_name: draft.display_name, description: draft.description, expression: draft.expression ?? "", status: draft.status } })); };
  const save = async (draft: SemanticDraft) => { await onUpdate(draft, draftValues[draft.id] ?? {}); setEditing(null); };
  return <section className="surface-panel semantic-detail" aria-labelledby="semantic-table-title">
    <div className="panel-heading"><div><button type="button" className="back-button" onClick={onBack}><Icon name="chevronRight" size={14} className="back-icon" /> 返回语义总览</button><div className="section-kicker">字段标注</div><h1 id="semantic-table-title">{table.name}</h1><p className="panel-subtitle">{table.row_count.toLocaleString()} 行 · {table.columns.length} 个字段。候选由扫描规则生成，修改后保存到共享 SQLite 草稿。</p></div></div>
    {error && <div className="error-banner"><Icon name="alert" size={15} /><span>{error}</span></div>}
    <div className="semantic-columns">{table.columns.map((column) => <div className="semantic-column-row" key={column.name}><div className="semantic-column-main"><strong>{column.name}</strong><span>{column.type} · {column.distinct_count} 个不同值 · {column.null_count} 个空值</span></div><div className="semantic-column-samples">{column.sample_values.slice(0, 3).map((value) => <span key={String(value)}>{String(value)}</span>)}</div></div>)}</div>
    <div className="semantic-draft-heading"><strong>语义候选</strong><span>确认后才能发布给 Agent</span></div>
    <div className="semantic-drafts">{table.drafts.map((draft) => { const values = draftValues[draft.id] ?? {}; const isEditing = editing === draft.id; return <div className="semantic-draft-row" key={draft.id}><div className="draft-badge">{draft.object_type}</div><div className="draft-main">{isEditing ? <><input className="semantic-input" value={String(values.display_name ?? "")} onChange={(event) => setDraftValues((current) => ({ ...current, [draft.id]: { ...current[draft.id], display_name: event.target.value } }))} /><textarea className="semantic-textarea" value={String(values.description ?? "")} onChange={(event) => setDraftValues((current) => ({ ...current, [draft.id]: { ...current[draft.id], description: event.target.value } }))} />{draft.expression !== null && <input className="semantic-input semantic-expression" value={String(values.expression ?? "")} onChange={(event) => setDraftValues((current) => ({ ...current, [draft.id]: { ...current[draft.id], expression: event.target.value } }))} />}<select className="semantic-input" value={String(values.status ?? draft.status)} onChange={(event) => setDraftValues((current) => ({ ...current, [draft.id]: { ...current[draft.id], status: event.target.value as SemanticDraft["status"] } }))}><option value="draft">待确认</option><option value="approved">确认</option><option value="rejected">忽略</option></select></> : <><strong>{draft.display_name}</strong><span>{draft.canonical_name} · {draft.source_column ?? "表级对象"}</span><p>{draft.description}</p></>}</div><div className="draft-evidence"><span className={`confidence confidence-${draft.confidence >= .9 ? "high" : draft.confidence >= .75 ? "medium" : "low"}`}>{Math.round(draft.confidence * 100)}%</span><small>{draft.evidence}</small></div><div className="draft-actions">{isEditing ? <button type="button" className="primary-button compact-button" onClick={() => void save(draft)} disabled={isBusy}><Icon name="check" size={13} /> 保存</button> : <button type="button" className="icon-button" onClick={() => beginEdit(draft)} title="编辑候选"><Icon name="annotation" size={15} /></button>}</div></div>; })}</div>
  </section>;
}
